### PR TITLE
attempt to fix the watermark being weird

### PR DESCRIPTION
**Pull request by MemeHoovy**
waiting for the workflow to finish

### CODE REVIEW

**Comment by LEVIXDDLMAO** [comment]
its sad there is no warning on the dodge

**Comment by MemeHoovy** [comment]
> its sad there is no warning on the dodge

I didn't add one yet

**Comment by LEVIXDDLMAO** [comment]
lol okay and its a bet buggy

**Comment by LEVIXDDLMAO** [comment]
space dosent work ( idk the dodge button

**Comment by LEVIXDDLMAO** [comment]
Ig im just bad bot play was able to do it

**Pull request merged**
