### PR TITLE
Fix win icons

### PR DESCRIPTION
**Pull request by MemeHoovy**
I legit wasn't done yet💀

### CODE REVIEW

**Comment by MemeHoovy** [comment]
you merged it too early

**Comment by LEVIXDDLMAO** [comment]
shit sorry

**Comment by MemeHoovy** [comment]
> shit sorry

It's fine, the PR should be good now

**Comment by LEVIXDDLMAO** [comment]
so should i push?

**Comment by MemeHoovy** [comment]
> so should i push?

ye

**Comment by LEVIXDDLMAO** [comment]
there

**Pull request merged**
