### PR TITLE
Bullet dodge thingamajig & fixed watermark for real this time

### PR DESCRIPTION
**Pull request by MemeHoovy**
the code for the bullet dodge thing is very scuffed and idk if it works though

### CODE REVIEW

**Comment by MemeHoovy** [comment]
I forgot some things

**Comment by LEVIXDDLMAO** [comment]
a okay

**Comment by MemeHoovy** [comment]
there we go, it's fixed now

**Comment by LEVIXDDLMAO** [comment]
i seen :D

**Comment by LEVIXDDLMAO** [comment]
is the dodge a event or an?

**Comment by MemeHoovy** [comment]
> is the dodge a event or an?

it's an event

**Comment by LEVIXDDLMAO** [comment]
okay ill check it out

**Comment by LEVIXDDLMAO** [comment]
do you think the bullet note works?

**Comment by MemeHoovy** [comment]
> do you think the bullet note works?

🤷🏻‍♂️

**Comment by LEVIXDDLMAO** [comment]
image
 Watermark isnt right

**Comment by LEVIXDDLMAO** [comment]
[index.webm](https://user-images.githubusercontent.com/92174516/192180798-3323d5a2-39e5-4fb1-a432-2be837b047ed.webm)

**Comment by LEVIXDDLMAO** [comment]
ello?

**Comment by MemeHoovy** [comment]
> ello?

I'm still here

**Comment by LEVIXDDLMAO** [comment]
ok ok

**Comment by LEVIXDDLMAO** [comment]
but thats when you try dodging

**Comment by MemeHoovy** [comment]
> but thats when you try dodging

yeah I gotta fix the timing

**Comment by LEVIXDDLMAO** [comment]
lol okay do you want me to add the alert

**Comment by MemeHoovy** [comment]
> lol okay do you want me to add the alert

ye sure, why not?

**Comment by LEVIXDDLMAO** [comment]
ok lol

**Comment by LEVIXDDLMAO** [comment]
there

**Comment by LEVIXDDLMAO** [comment]
did you fix it?

**Comment by MemeHoovy** [comment]
> did you fix it?

not yet, but I'll get to it

**Comment by LEVIXDDLMAO** [comment]
okay

**Pull request merged**
